name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Build the Docker image
      run: docker build -t webserver:$(date +%s) . && docker image prune -f
